using Dapper;
using MISA.AMIS.Common.DTO;
using MISA.AMIS.Common.Entities;
using MISA.AMIS.Common.Enums;
using MySqlConnector;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MISA.AMIS.DL
{
    public class EmployeeDL : BaseDL<Employee>, IEmployeeDL
    {
        public PagingResult<Employee> GetByFilter(PagingRequest request)
        {
            return new PagingResult<Employee> { TotalPage = 1, TotalRecord = 10, Data = new List<Employee> {  new Employee{
        EmployeeID = new Guid("11131abd-1b99-688b-96f6-423b4e874d0f"),
        EmployeeCode = "NV20113",
        EmployeeName = "Ngô Đình Khánh",
        DateOfBirth = DateTime.Now,
        Gender = Gender.Male,
        Address = "3731 N Social Pkwy, Comcast Bldg, Concord, NH, 77822",
        Email = "NigelMercier6@example.com",
        PhoneNumber = "0873808795",
        TelephoneNumber = "(769) 119-5059",
        IdentityNumber = "034616472838",
        IdentityDate = DateTime.Now,
        IdentityPlace = "Cục Cảnh sát quản lý hành chính về trật tự xã hội",
        Salary = 80935.006,
        BankAccountNumber = "43060",
        BankName = "KOIF VN J4 RKB",
        BankBranchName = "XFCI SR U6",
        BankProvinceName = "",
        JoinDate = DateTime.Now,
        WorkStatus = 0,
        DepartmentID = new Guid("469b3ece-744a-45d5-957d-e8c757976496"),
        PositionName = "Phòng bảo vệ",
        CreatedDate = DateTime.Now,
        CreatedBy = "Long Mai",
        ModifiedDate = DateTime.Now,
        ModifiedBy = "Long"
    },
    new Employee{
        EmployeeID = new Guid("11326c16-72e5-61b3-82c2-579daad24557"),
        EmployeeCode = "NV18145",
        EmployeeName = "Trần Thảo Ánh",
        DateOfBirth = DateTime.Now,
        Gender = Gender.Male,
        Address = "3463 Edgewood Ct, 3rd Floor, Frankfort, KY, 80590",
        Email = "Conrad874@example.com",
        PhoneNumber = "0203956922",
        TelephoneNumber = "(769) 628-4676",
        IdentityNumber = "032720982547",
        IdentityDate = DateTime.Now,
        IdentityPlace = "Cục Cảnh sát quản lý hành chính về trật tự xã hội",
        Salary = 111846.3172,
        BankAccountNumber = "78183",
        BankName = "KBMA JO P7 8LC",
        BankBranchName = "OUJR AF P5 L6O",
        BankProvinceName = "EFCA NG GZ 769",
        JoinDate = DateTime.Now,
        WorkStatus = 0,
        DepartmentID = new Guid(),
        PositionName = null,
        CreatedDate = DateTime.Now,
        CreatedBy = "Freddie Wilkes",
        ModifiedDate = DateTime.Now,
        ModifiedBy = "SX0PI"
    },
    new Employee{
        EmployeeID = new Guid("1170a168-2949-6f39-dfd2-89b22d10517e"),
        EmployeeCode = "NV18168",
        EmployeeName = "Vũ Xuân Dương",
        DateOfBirth = DateTime.Now,
        Gender = Gender.Male,
        Address = "1869 East Deepwood Circle, Buhl Bldg, Jefferson City, MO, 69528",
        Email = "Patrica_Conaway64@nowhere.com",
        PhoneNumber = "0328473708",
        TelephoneNumber = "(503) 577-6956",
        IdentityNumber = "035720501316",
        IdentityDate = DateTime.Now,
        IdentityPlace = "Cục Cảnh sát quản lý hành chính về trật tự xã hội",
        Salary = 95514.7956,
        BankAccountNumber = "42819",
        BankName = "OQQQ WS OM",
        BankBranchName = "WCBQ LB K0",
        BankProvinceName = "XHFK BH 4L 1ZN",
        JoinDate = DateTime.Now,
        WorkStatus = 2,
        DepartmentID = new Guid(),
        PositionName = null,
        CreatedDate = DateTime.Now,
        CreatedBy = "Ginger Brackett",
        ModifiedDate = DateTime.Now,
        ModifiedBy = "P2717YEQ72Y657D"
    },
    new Employee{
        EmployeeID = new Guid("117d03f4-5df7-183b-7335-0028ed526dd0"),
        EmployeeCode = "NV92651",
        EmployeeName = "Nguyễn Bảo Dương",
        DateOfBirth = DateTime.Now,
        Gender = Gender.Male,
        Address = "47 Old Social Ln, Equitable Bldg, Helena, Montana, 65086",
        Email = "Thatcher@example.com",
        PhoneNumber = "0209639512",
        TelephoneNumber = "(503) 549-0586",
        IdentityNumber = "031237105801",
        IdentityDate = DateTime.Now,
        IdentityPlace = "Cục Cảnh sát quản lý hành chính về trật tự xã hội",
        Salary = 55403.7665,
        BankAccountNumber = "98042",
        BankName = "MSZF ZM MC 1J8",
        BankBranchName = "USRS PE R3",
        BankProvinceName = "TYAK MN W6",
        JoinDate = DateTime.Now,
        WorkStatus = 1,
        DepartmentID = new Guid(),
        PositionName = null,
        CreatedDate = DateTime.Now,
        CreatedBy = "Fausto Ibarra",
        ModifiedDate = DateTime.Now,
        ModifiedBy = "1X587I5I48WZKCRAMAH6513J01W"
    },
    new Employee{
        EmployeeID = new Guid("119033a8-7095-5b6f-7435-0028ed526dd0"),
        EmployeeCode = "NV50105",
        EmployeeName = "Lê Minh Vy",
        DateOfBirth = DateTime.Now,
        Gender = Gender.Male,
        Address = "2314 Brentwood Way, Phoenix, Arizona, 94236",
        Email = "Chang@example.com",
        PhoneNumber = "0908319659",
        TelephoneNumber = "(239) 304-5777",
        IdentityNumber = "038895129703",
        IdentityDate = DateTime.Now,
        IdentityPlace = "Cục Cảnh sát quản lý hành chính về trật tự xã hội",
        Salary = 75016.7564,
        BankAccountNumber = "23945",
        BankName = "QCYA FJ 1P",
        BankBranchName = "BOQM RO 04 4AR",
        BankProvinceName = "FJZG KE W8 113",
        JoinDate = DateTime.Now,
        WorkStatus = 2,
        DepartmentID = new Guid(),
        PositionName = null,
        CreatedDate = DateTime.Now,
        CreatedBy = "Arturo Redd",
        ModifiedDate = DateTime.Now,
        ModifiedBy = "VZO23G12J23Q0974YIGNVT1TZKW7VV7TW3U936"
    },
    new Employee{
        EmployeeID = new Guid("11a8748f-3464-740c-28c2-579daad24557"),
        EmployeeCode = "NV39603",
        EmployeeName = "Ngô Tuấn Khánh",
        DateOfBirth = DateTime.Now,
        Gender = Gender.Male,
        Address = "2526 West Pine Tree Highway, Diamond Building, Salt Lake City, Utah, 01418",
        Email = "Kiefer@nowhere.com",
        PhoneNumber = "0876922631",
        TelephoneNumber = "(127) 273-8561",
        IdentityNumber = "035690571067",
        IdentityDate = DateTime.Now,
        IdentityPlace = "Cục Cảnh sát quản lý hành chính về trật tự xã hội",
        Salary = 73848.7978,
        BankAccountNumber = "28810",
        BankName = "HVGS AF FF",
        BankBranchName = "LRUK IS W2 ZE0",
        BankProvinceName = "BYMV RO 8K TKX",
        JoinDate = DateTime.Now,
        WorkStatus = 1,
        DepartmentID = new Guid(),
        PositionName = null,
        CreatedDate = DateTime.Now,
        CreatedBy = "Loise Mayers",
        ModifiedDate = DateTime.Now,
        ModifiedBy = "HWM"
    },
    new Employee{
        EmployeeID = new Guid("11d15295-2324-7403-261e-086412a8ea97"),
        EmployeeCode = "NV80139",
        EmployeeName = "Trần Tuấn Độ",
        DateOfBirth = DateTime.Now,
        Gender = Gender.Male,
        Address = "1998 Sharp Hill Dr, Des Moines, Iowa, 40538",
        Email = "OleneSantiago1@example.com",
        PhoneNumber = "0209716620",
        TelephoneNumber = "(571) 463-7072",
        IdentityNumber = "036151650523",
        IdentityDate = DateTime.Now,
        IdentityPlace = "Cục Cảnh sát quản lý hành chính về trật tự xã hội",
        Salary = 47948.9183,
        BankAccountNumber = "58805",
        BankName = "TIBI SL 2H 7B1",
        BankBranchName = "DXEG MT IR",
        BankProvinceName = "JFQM BG 64",
        JoinDate = DateTime.Now,
        WorkStatus = 0,
        DepartmentID = new Guid(),
        PositionName = null,
        CreatedDate = DateTime.Now,
        CreatedBy = "Julian Kane",
        ModifiedDate = DateTime.Now,
        ModifiedBy = "A2233PCS746G6FV4C060JF8AT4599MBGU7MC6"
    },
    new Employee{
        EmployeeID = new Guid("11e8faef-6121-695a-86f6-423b4e874d0f"),
        EmployeeCode = "NV28592",
        EmployeeName = "Ngô Thảo Ánh",
        DateOfBirth = DateTime.Now,
        Gender = Gender.Male,
        Address = "1191 S Highland Pkwy, SalEm, OR, 41461",
        Email = "Pollock5@nowhere.com",
        PhoneNumber = "0204143209",
        TelephoneNumber = "(622) 706-6109",
        IdentityNumber = "037039034279",
        IdentityDate = DateTime.Now,
        IdentityPlace = "Cục Cảnh sát quản lý hành chính về trật tự xã hội",
        Salary = 22523.4768,
        BankAccountNumber = "34076",
        BankName = "OTQE CU 1I EXW",
        BankBranchName = "SXFG EE 21",
        BankProvinceName = "QERY PY ZB 90G",
        JoinDate = DateTime.Now,
        WorkStatus = 1,
        DepartmentID = new Guid(),
        PositionName = null,
        CreatedDate = DateTime.Now,
        CreatedBy = "Adolfo Schafer",
        ModifiedDate = DateTime.Now,
        ModifiedBy = "448"
    },
    new Employee{
        EmployeeID = new Guid(),
        EmployeeCode = "NV76611",
        EmployeeName = "Đinh Phương Phương",
        DateOfBirth = DateTime.Now,
        Gender = Gender.Male,
        Address = "438 W Beachwood Way, Phoenix, AZ, 14908",
        Email = "CletaAbney7@example.com",
        PhoneNumber = "0873795863",
        TelephoneNumber = "(202) 031-3680",
        IdentityNumber = "033934304911",
        IdentityDate = DateTime.Now,
        IdentityPlace = "Cục Cảnh sát quản lý hành chính về trật tự xã hội",
        Salary = 21962.2348,
        BankAccountNumber = "95093",
        BankName = "HGWD GY W1 U01",
        BankBranchName = "KXOL GM 4G EAY",
        BankProvinceName = "UTJO AL 94",
        JoinDate = DateTime.Now,
        WorkStatus = 1,
        DepartmentID = new Guid(),
        PositionName = null,
        CreatedDate = DateTime.Now,
        CreatedBy = "Geraldine Trammell",
        ModifiedDate = DateTime.Now,
        ModifiedBy = "0E8H05C0DPJGH4B4J537CB5LOL2U1IWG6KC690AQ6"
    },
    new Employee{
        EmployeeID = new Guid(),
        EmployeeCode = "NV64319",
        EmployeeName = "Lý Minh Anh",
        DateOfBirth = DateTime.Now,
        Gender = Gender.Male,
        Address = "1163 2nd Ave, Penobscot Building, Boise, Idaho, 07957",
        Email = "Garmon21@example.com",
        PhoneNumber = "0205521315",
        TelephoneNumber = "(252) 425-3120",
        IdentityNumber = "036868284475",
        IdentityDate = DateTime.Now,
        IdentityPlace = "Cục Cảnh sát quản lý hành chính về trật tự xã hội",
        Salary = 21571.2975,
        BankAccountNumber = "27112",
        BankName = "KXPL FI RX 8BE",
        BankBranchName = "PULA SL N6 25O",
        BankProvinceName = "IIRI MN H9",
        JoinDate = DateTime.Now,
        WorkStatus = 2,
        DepartmentID = new Guid(),
        PositionName = null,
        CreatedDate = DateTime.Now,
        CreatedBy = "Brooke Cartwright",
        ModifiedDate = DateTime.Now,
        ModifiedBy = "O769M66E6DC9IPU738QZPK1VLMW62K8D54W2XIMZX5618V4B38M9616YF084C80YXYZ"
    }, } };
        }
    }
}
